name: "Update Flakes"
on:
#  schedule:
#  - cron:  '00 18 * * 1'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  flake_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - run: nix flake update
    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
      with:
        commit_message: nix flake update
    - run: nix flake update
      working-directory: example
    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
      with:
        commit_message: "example: nix flake update"
